<a href="https://colab.research.google.com/github/adyanshkakran/Mechanistic_Interpretability/blob/main/InterpretingTransformers_Bracket_Matching.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Grokking Demo Notebook

<b style="color: red">To use this notebook, go to Runtime > Change Runtime Type and select GPU as the hardware accelerator.</b>

# Setup
(No need to read)

In [ ]:
TRAIN_MODEL = True

In [ ]:
!nvidia-smi

Mon Mar  4 14:16:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Janky code to do different setup when run in a Colab notebook vs VSCode
DEVELOPMENT_MODE = True
try:
    import google.colab
    IN_COLAB = True
    print("Running as a Colab notebook")
    %pip install transformer-lens
    %pip install circuitsvis

    # PySvelte is an unmaintained visualization library, use it as a backup if circuitsvis isn't working
    # # Install another version of node that makes PySvelte work way faster
    # !curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -; sudo apt-get install -y nodejs
    # %pip install git+https://github.com/neelnanda-io/PySvelte.git
except:
    IN_COLAB = False
    print("Running as a Jupyter notebook - intended for development only!")
    from IPython import get_ipython

    ipython = get_ipython()
    # Code to automatically update the HookedTransformer code as its edited without restarting the kernel
    ipython.magic("load_ext autoreload")
    ipython.magic("autoreload 2")

Running as a Colab notebook
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.9/122.9 kB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.0/280.0 kB 12.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 739.7/739.7 kB 15.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 17.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 61.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 15.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 17.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 41.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 50.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 57.4 MB/s e

In [ ]:
# Plotly needs a different renderer for VSCode/Notebooks vs Colab argh
import plotly.io as pio
if IN_COLAB or not DEVELOPMENT_MODE:
    pio.renderers.default = "colab"
else:
    pio.renderers.default = "notebook_connected"
print(f"Using renderer: {pio.renderers.default}")

Using renderer: colab


In [ ]:
pio.templates['plotly'].layout.xaxis.title.font.size = 20
pio.templates['plotly'].layout.yaxis.title.font.size = 20
pio.templates['plotly'].layout.title.font.size = 30

In [ ]:
# Import stuff
import torch
import torch.nn as nn
import pandas as pd
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import einops
from fancy_einsum import einsum
import os
import tqdm.auto as tqdm
import random
from pathlib import Path
import plotly.express as px
from torch.utils.data import DataLoader

from typing import List, Union, Optional
from functools import partial
import copy

# import itertools
# from transformers import AutoModelForCausalLM, AutoConfig, AutoTokenizer
# import dataclasses
# import datasets
# from IPython.display import HTML

In [ ]:
import transformer_lens
import transformer_lens.utils as utils
from transformer_lens.hook_points import (
    HookedRootModule,
    HookPoint,
)  # Hooking utilities
from transformer_lens import HookedTransformer, HookedTransformerConfig, FactoredMatrix, ActivationCache

Plotting helper functions:

In [ ]:
def imshow(tensor, renderer=None, xaxis="", yaxis="", **kwargs):
    px.imshow(utils.to_numpy(tensor), color_continuous_midpoint=0.0, color_continuous_scale="RdBu", labels={"x":xaxis, "y":yaxis}, **kwargs).show(renderer)

def line(tensor, renderer=None, xaxis="", yaxis="", **kwargs):
    px.line(utils.to_numpy(tensor), labels={"x":xaxis, "y":yaxis}, **kwargs).show(renderer)

def scatter(x, y, xaxis="", yaxis="", caxis="", renderer=None, **kwargs):
    x = utils.to_numpy(x)
    y = utils.to_numpy(y)
    px.scatter(y=y, x=x, labels={"x":xaxis, "y":yaxis, "color":caxis}, **kwargs).show(renderer)

In [ ]:
# Define the location to save the model, using a relative path
PTH_LOCATION = "workspace/_scratch/grokking_demo.pth"

# Create the directory if it does not exist
os.makedirs(Path(PTH_LOCATION).parent, exist_ok=True)

# Model Training

## Config

In [ ]:
p = 51
frac_train = 0.3

# Optimizer config
lr = 1e-3
wd = 1.
betas = (0.9, 0.98)

num_epochs = 2000
checkpoint_every = 20

DATA_SEED = 598

## Define Task
* Define modular addition
* Define the dataset & labels

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
import csv

In [ ]:
# create string tensors to store the strings and labels
a_strings = []
labels = []
with open('/content/balanced_brackets.csv') as csvfile:
    data = list(csv.reader(csvfile))
    data = data[1:]
    for line in data:
        a, label = line[0], int(line[1])
        a_strings.append(a)
        labels.append(label)

In [ ]:
len(a_strings),  len(labels)

(12000, 12000)

In [ ]:
# get the longest string length
max_len_a = max([len(s) for s in a_strings])
print(max_len_a)

# max_str = max(strings, key=len)
# max_str

64


In [ ]:

unique_labels = ['[','{', '(', ')','}',']']

In [ ]:
chars = {}
count = 0
for label in unique_labels:
  for char in label:
    if char not in chars:
      chars[char] = count
      count+=1
chars

{'[': 0, '{': 1, '(': 2, ')': 3, '}': 4, ']': 5}

In [ ]:
def string_to_tensor(string, max_length=64):
    # Convert characters to numerical values
    char_to_int = chars
    tensor = [char_to_int[char] for char in string]

    # Pad the tensor to the max_length with 0
    tensor += [0] * (max_length - len(tensor))

    return tensor

def label_to_tensor(label, unique_labels=[0,1]):
    # Convert the label to a one-hot tensor
    label_tensor = [0] * len(unique_labels)
    label_tensor[label] = 1

    return label_tensor

In [ ]:
# Convert the strings to tensors
input_tensors_a = torch.from_numpy(np.array([string_to_tensor(s) for s in a_strings]))
input_tensors_a.shape

torch.Size([12000, 64])

In [ ]:
label_tensors = torch.from_numpy(np.array([label_to_tensor(l) for l in labels]))
label_tensors.shape

torch.Size([12000, 2])

In [ ]:
# print the first 5 input and label tensors
for i in range(5):
    print(input_tensors_a[i], label_tensors[i])

tensor([2, 5, 4, 2, 5, 3, 1, 1, 0, 0, 0, 3, 4, 2, 0, 5, 1, 3, 0, 3, 3, 0, 3, 1,
        2, 2, 3, 4, 1, 2, 4, 3, 4, 0, 1, 3, 3, 3, 0, 5, 4, 3, 1, 5, 2, 3, 3, 1,
        3, 2, 1, 1, 5, 5, 2, 1, 3, 1, 0, 1, 4, 2, 2, 5]) tensor([1, 0])
tensor([3, 2, 3, 2, 0, 5, 5, 2, 2, 1, 3, 1, 5, 0, 3, 0, 0, 3, 5, 1, 5, 5, 2, 4,
        2, 4, 1, 2, 1, 0, 2, 5, 5, 4, 0, 5, 0, 2, 2, 2, 2, 5, 5, 5, 1, 5, 3, 2,
        3, 3, 3, 1, 1, 1, 5, 3, 2, 4, 3, 2, 5, 1, 4, 4]) tensor([1, 0])
tensor([1, 2, 3, 1, 1, 4, 2, 3, 4, 4, 0, 2, 0, 0, 1, 4, 5, 5, 1, 4, 3, 5, 0, 5,
        0, 0, 5, 5, 0, 2, 2, 3, 3, 1, 0, 2, 1, 4, 1, 1, 1, 2, 3, 0, 5, 1, 4, 2,
        3, 4, 2, 2, 3, 3, 4, 4, 2, 3, 3, 0, 5, 5, 4, 5]) tensor([0, 1])
tensor([3, 4, 5, 1, 4, 3, 0, 3, 3, 3, 4, 2, 0, 3, 1, 3, 0, 1, 2, 1, 5, 0, 1, 2,
        2, 1, 1, 1, 0, 5, 4, 4, 3, 4, 1, 5, 2, 4, 2, 5, 5, 2, 3, 1, 1, 1, 5, 4,
        2, 4, 1, 0, 4, 3, 3, 0, 2, 5, 4, 1, 4, 5, 0, 3]) tensor([1, 0])
tensor([0, 2, 3, 5, 3, 1, 1, 1, 4, 0, 1, 0, 0, 2, 2, 5, 4, 0, 5, 3, 3, 5

Input format:
|a|b|=|

In [ ]:
dataset = input_tensors_a.cuda()
print(dataset[:5])
print(dataset.shape)

tensor([[2, 5, 4, 2, 5, 3, 1, 1, 0, 0, 0, 3, 4, 2, 0, 5, 1, 3, 0, 3, 3, 0, 3, 1,
         2, 2, 3, 4, 1, 2, 4, 3, 4, 0, 1, 3, 3, 3, 0, 5, 4, 3, 1, 5, 2, 3, 3, 1,
         3, 2, 1, 1, 5, 5, 2, 1, 3, 1, 0, 1, 4, 2, 2, 5],
        [3, 2, 3, 2, 0, 5, 5, 2, 2, 1, 3, 1, 5, 0, 3, 0, 0, 3, 5, 1, 5, 5, 2, 4,
         2, 4, 1, 2, 1, 0, 2, 5, 5, 4, 0, 5, 0, 2, 2, 2, 2, 5, 5, 5, 1, 5, 3, 2,
         3, 3, 3, 1, 1, 1, 5, 3, 2, 4, 3, 2, 5, 1, 4, 4],
        [1, 2, 3, 1, 1, 4, 2, 3, 4, 4, 0, 2, 0, 0, 1, 4, 5, 5, 1, 4, 3, 5, 0, 5,
         0, 0, 5, 5, 0, 2, 2, 3, 3, 1, 0, 2, 1, 4, 1, 1, 1, 2, 3, 0, 5, 1, 4, 2,
         3, 4, 2, 2, 3, 3, 4, 4, 2, 3, 3, 0, 5, 5, 4, 5],
        [3, 4, 5, 1, 4, 3, 0, 3, 3, 3, 4, 2, 0, 3, 1, 3, 0, 1, 2, 1, 5, 0, 1, 2,
         2, 1, 1, 1, 0, 5, 4, 4, 3, 4, 1, 5, 2, 4, 2, 5, 5, 2, 3, 1, 1, 1, 5, 4,
         2, 4, 1, 0, 4, 3, 3, 0, 2, 5, 4, 1, 4, 5, 0, 3],
        [0, 2, 3, 5, 3, 1, 1, 1, 4, 0, 1, 0, 0, 2, 2, 5, 4, 0, 5, 3, 3, 5, 5, 0,
         4, 5, 2, 2, 1, 0, 5, 0, 1, 1, 

In [ ]:
# labels = (dataset[:, 0] + dataset[:, 1]) % p
# print(labels.shape)
# print(labels[:5])

labels = torch.tensor(label_tensors)
print(labels[:5])
print(labels.shape)

tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0]])
torch.Size([12000, 2])


<ipython-input-23-bdea7e19661c>:5: UserWarning:

To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).



Convert this to a train + test set - 30% in the training set

In [ ]:
# torch.manual_seed(DATA_SEED)
# indices = torch.randperm(p*p)
# cutoff = int(p*p*frac_train)
# train_indices = indices[:cutoff]
# test_indices = indices[cutoff:]

# train_data = dataset[train_indices]
# train_labels = labels[train_indices]
# test_data = dataset[test_indices]
# test_labels = labels[test_indices]
# print(train_data[:5])
# print(train_labels[:5])
# print(train_data.shape)
# print(test_data[:5])
# print(test_labels[:5])
# print(test_data.shape)

# get the train and test data sampled randomly
torch.manual_seed(DATA_SEED)

# shuffle the data
indices = torch.randperm(len(dataset))
dataset = dataset[indices]
labels = labels[indices]

# split the data into train and test
train_cutoff = int(len(dataset) * frac_train)
train_data = dataset[:train_cutoff]
train_labels = labels[:train_cutoff]
test_data = dataset[train_cutoff:]
test_labels = labels[train_cutoff:]

In [ ]:
# create attention masks
train_attention_mask = (train_data != 0).float()
test_attention_mask = (test_data != 0).float()

train_attention_mask[:5], test_attention_mask[:5]

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
          1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
          1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
          1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
         [1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1.,
          1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
          1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1

In [ ]:
print(train_data[:5])
print(train_labels[:5])

print(train_data.shape)
print(test_data.shape)


tensor([[4, 3, 5, 2, 2, 3, 2, 3, 0, 2, 1, 4, 4, 1, 2, 0, 4, 4, 3, 3, 2, 0, 4, 4,
         0, 2, 3, 1, 3, 0, 3, 2, 4, 4, 3, 2, 1, 1, 0, 1, 2, 4, 1, 3, 2, 2, 5, 5,
         2, 0, 1, 0, 1, 5, 2, 4, 3, 0, 4, 4, 1, 1, 5, 3],
        [1, 0, 3, 5, 4, 4, 1, 0, 3, 2, 3, 3, 3, 5, 4, 1, 1, 3, 3, 4, 1, 1, 1, 3,
         5, 3, 3, 1, 1, 4, 4, 0, 0, 0, 5, 3, 2, 0, 0, 4, 1, 2, 2, 0, 3, 1, 5, 3,
         4, 1, 5, 3, 2, 2, 4, 3, 1, 5, 4, 3, 4, 3, 4, 1],
        [1, 4, 1, 0, 1, 2, 1, 0, 1, 4, 5, 4, 2, 2, 2, 3, 1, 1, 4, 4, 2, 1, 4, 2,
         2, 3, 3, 3, 2, 3, 3, 3, 0, 0, 1, 4, 2, 1, 0, 5, 4, 3, 2, 3, 2, 0, 1, 0,
         5, 1, 0, 5, 0, 5, 4, 4, 5, 3, 5, 5, 3, 4, 5, 4],
        [0, 0, 3, 0, 3, 0, 4, 1, 2, 0, 1, 4, 3, 2, 5, 1, 4, 1, 2, 2, 1, 5, 2, 2,
         0, 5, 2, 0, 1, 0, 2, 5, 0, 0, 3, 5, 0, 2, 1, 3, 1, 0, 3, 4, 1, 5, 0, 3,
         5, 3, 2, 5, 5, 0, 5, 4, 1, 5, 2, 2, 3, 2, 3, 2],
        [3, 1, 5, 0, 0, 3, 0, 0, 3, 3, 5, 0, 4, 5, 4, 1, 0, 5, 2, 4, 2, 0, 5, 4,
         3, 4, 1, 5, 0, 2, 4, 0, 3, 5, 

In [ ]:
from torch.utils.data import DataLoader, TensorDataset

In [ ]:
train_dataset = TensorDataset(train_data, train_labels)
test_dataset = TensorDataset(test_data, test_labels)


In [ ]:
batch_size=64

# Create DataLoader for train and test data
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size)

## Define Model

In [ ]:
cfg = HookedTransformerConfig(
    n_layers = 1,
    n_heads = 4,
    d_model = 128,
    d_head = 32,
    d_mlp = 512,
    act_fn = "relu",
    normalization_type=None,
    d_vocab=6, # Number of unique characters in vocab
    d_vocab_out=2, # Number of classes
    n_ctx=64,
    init_weights=True,
    # device="cuda",
    seed = 999,
)

In [ ]:
model = HookedTransformer(cfg)

Disable the biases, as we don't need them for this task and it makes things easier to interpret.

In [ ]:
for name, param in model.named_parameters():
    if "b_" in name:
        param.requires_grad = False


In [ ]:
# # sample
# train_logits = model(train_data)
# print(train_logits.shape)
# print(train_logits[0])

## Define Optimizer + Loss

In [ ]:
optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=wd, betas=betas)

In [ ]:
def loss_fn(logits, labels):
    if len(logits.shape)==3:
        logits = logits[:, -1]
    logits = logits.to(torch.float64)
    labels = labels.to(torch.float64)
    # do softmax
    logits = F.log_softmax(logits, dim=-1)
    # compute the cross entropy
    loss = nn.CrossEntropyLoss()
    return loss(logits, labels)

# train_logits = model.forward(train_data, attention_mask=train_attention_mask)
# train_loss = loss_fn(train_logits, train_labels)
# print(train_loss)
# test_logits = model(test_data)
# test_loss = loss_fn(test_logits, test_labels)
# print(test_loss)

In [ ]:
print("Uniform loss:")
print(np.log(p))

Uniform loss:
3.9318256327243257


## Actually Train

**Weird Decision:** Training the model with full batch training rather than stochastic gradient descent. We do this so to make training smoother and reduce the number of slingshots.

In [ ]:
train_losses = []
test_losses = []
model_checkpoints = []
checkpoint_epochs = []
if TRAIN_MODEL:
    for epoch in tqdm.tqdm(range(num_epochs)):
        # Training loop
        model.train()
        batch_train_loss = []
        for batch_data, batch_labels in train_loader:
            optimizer.zero_grad()
            train_logits = model.forward(batch_data.cuda())
            train_loss = loss_fn(train_logits, batch_labels.cuda())
            train_loss.backward()
            optimizer.step()
            batch_train_loss.append(train_loss.item())
        train_losses.append(np.mean(batch_train_loss))

        # Testing loop
        model.eval()
        batch_test_loss = []
        with torch.inference_mode():
            for batch_data, batch_labels in test_loader:
                test_logits = model.forward(batch_data.cuda())
                test_loss = loss_fn(test_logits, batch_labels.cuda())
                batch_test_loss.append(test_loss.item())
            test_losses.append(np.mean(batch_test_loss))

        # Print and save checkpoints
        if ((epoch+1) % checkpoint_every) == 0:
            checkpoint_epochs.append(epoch)
            model_checkpoints.append(copy.deepcopy(model.state_dict()))
            print(f"Epoch {epoch} Train Loss {train_loss.item()} Test Loss {test_loss.item()}")

  0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 19 Train Loss 0.03377853857914484 Test Loss 0.032477961204307876
Epoch 39 Train Loss 0.4211940762497749 Test Loss 0.03639761485550804
Epoch 59 Train Loss 0.2824902223341336 Test Loss 0.07094633890192938
Epoch 79 Train Loss 0.2732674297303203 Test Loss 0.08000082863064181
Epoch 99 Train Loss 0.029705782945590932 Test Loss 0.06508750350122271
Epoch 119 Train Loss 0.23519306037813933 Test Loss 0.15415702574468607
Epoch 139 Train Loss 0.055780951745448636 Test Loss 0.056240190503555304
Epoch 159 Train Loss 0.24232528712718243 Test Loss 0.03434164923889074
Epoch 179 Train Loss 0.6385613741012124 Test Loss 1.1453266652623366
Epoch 199 Train Loss 0.15892164018834748 Test Loss 0.03848755477319497
Epoch 219 Train Loss 0.2555989176466767 Test Loss 0.08789470633348842
Epoch 239 Train Loss 0.11927280698693807 Test Loss 0.06738643064641739
Epoch 259 Train Loss 0.05213915208037553 Test Loss 0.05889522197279586
Epoch 279 Train Loss 0.13867320826191448 Test Loss 0.06651266911882095
Epoch 299 Tra

In [ ]:
# prompt: do inference with test set and create classification report

# Do inference on the test set
model.eval()
test_logits = model(test_data)

if len(test_logits.shape) == 3:
    test_logits = test_logits[:, -1]

test_logits = torch.nn.functional.softmax(test_logits, dim=1)
test_logits = torch.argmax(test_logits, dim=1)

predicted_labels = torch.nn.functional.one_hot(test_logits, 2)
print(test_logits.shape)

from sklearn.metrics import classification_report, accuracy_score
print(classification_report(test_labels, predicted_labels.cpu().numpy()))
print(f"Accuracy: {accuracy_score(test_labels, predicted_labels.cpu().numpy()) * 100} %")


torch.Size([8400])
              precision    recall  f1-score   support

           0       0.98      0.95      0.97      7019
           1       0.79      0.90      0.84      1381

   micro avg       0.94      0.94      0.94      8400
   macro avg       0.88      0.93      0.90      8400
weighted avg       0.95      0.94      0.95      8400
 samples avg       0.94      0.94      0.94      8400

Accuracy: 94.38095238095238 %


In [ ]:
torch.save(
    {
        "model":model.state_dict(),
        "config": model.cfg,
        "checkpoints": model_checkpoints,
        "checkpoint_epochs": checkpoint_epochs,
        "test_losses": test_losses,
        "train_losses": train_losses,
        # "train_indices": train_indices,
        # "test_indices": test_indices,
    },
    PTH_LOCATION)

In [ ]:
if not TRAIN_MODEL:
    cached_data = torch.load(PTH_LOCATION)
    model.load_state_dict(cached_data['model'])
    model_checkpoints = cached_data["checkpoints"]
    checkpoint_epochs = cached_data["checkpoint_epochs"]
    test_losses = cached_data['test_losses']
    train_losses = cached_data['train_losses']
    # train_indices = cached_data["train_indices"]
    # test_indices = cached_data["test_indices"]

## Show Model Training Statistics, Check that it groks!

In [ ]:
%pip install git+https://github.com/neelnanda-io/neel-plotly.git
from neel_plotly.plot import line

  Cloning https://github.com/neelnanda-io/neel-plotly.git to /tmp/pip-req-build-0h_hh8nb
  Running command git clone --filter=blob:none --quiet https://github.com/neelnanda-io/neel-plotly.git /tmp/pip-req-build-0h_hh8nb
  Resolved https://github.com/neelnanda-io/neel-plotly.git to commit 6dc24b26f8dec991908479d7445dae496b3430b7
  Preparing metadata (setup.py) ... done
  Created wheel for neel-plotly: filename=neel_plotly-0.0.0-py3-none-any.whl size=10186 sha256=a9c00b1cf927b54d8c09a3515a057871ff52af7a6ebeb54fa66fc6cacae18bc4
  Stored in directory: /tmp/pip-ephem-wheel-cache-eeij971f/wheels/32/cf/25/0103b4be02266c40faf008ffa9565a2ba07d1c63118fccc390
Successfully built neel-plotly


In [ ]:
train_losses_2 = np.asarray(train_losses).astype('float64')
test_losses_2 = np.asarray(test_losses).astype('float64')
line([train_losses_2[::10], test_losses_2[::10]], x=np.arange(0, len(train_losses_2), 10), xaxis="Epoch", yaxis="Loss", log_y=True, title="Training Curve for Bracket Matching", line_labels=['train', 'test'], toggle_x=True, toggle_y=True)

# Analysing the Model

In [ ]:
for i in dataset:
  print(i)
  break

## Standard Things to Try

In [ ]:
original_logits, cache = model.run_with_cache(dataset)
print(original_logits.numel())

1536000


In [ ]:
original_logits.shape

torch.Size([12000, 64, 2])

Get key weight matrices:

In [ ]:
W_E = model.embed.W_E[:-1]
print("W_E", W_E.shape)
W_neur = W_E @ model.blocks[0].attn.W_V @ model.blocks[0].attn.W_O @ model.blocks[0].mlp.W_in
print("W_neur", W_neur.shape)
W_logit = model.blocks[0].mlp.W_out @ model.unembed.W_U
print("W_logit", W_logit.shape)

W_E torch.Size([5, 128])
W_neur torch.Size([4, 5, 512])
W_logit torch.Size([512, 2])


In [ ]:
original_loss = loss_fn(original_logits, labels.to('cuda')).item()
print("Original Loss:", original_loss)

Original Loss: 0.13373249664471742


### Looking at Activations

Helper variable:

In [ ]:
pattern_a = cache["pattern", 0, "attn"][:, :, -1, 0]
pattern_b = cache["pattern", 0, "attn"][:, :, -1, 1]
neuron_acts = cache["post", 0, "mlp"][:, -1, :]
neuron_pre_acts = cache["pre", 0, "mlp"][:, -1, :]

Get all shapes:

In [ ]:
for param_name, param in cache.items():
    print(param_name, param.shape)

hook_embed torch.Size([12000, 64, 128])
hook_pos_embed torch.Size([12000, 64, 128])
blocks.0.hook_resid_pre torch.Size([12000, 64, 128])
blocks.0.attn.hook_q torch.Size([12000, 64, 4, 32])
blocks.0.attn.hook_k torch.Size([12000, 64, 4, 32])
blocks.0.attn.hook_v torch.Size([12000, 64, 4, 32])
blocks.0.attn.hook_attn_scores torch.Size([12000, 4, 64, 64])
blocks.0.attn.hook_pattern torch.Size([12000, 4, 64, 64])
blocks.0.attn.hook_z torch.Size([12000, 64, 4, 32])
blocks.0.hook_attn_out torch.Size([12000, 64, 128])
blocks.0.hook_resid_mid torch.Size([12000, 64, 128])
blocks.0.mlp.hook_pre torch.Size([12000, 64, 512])
blocks.0.mlp.hook_post torch.Size([12000, 64, 512])
blocks.0.hook_mlp_out torch.Size([12000, 64, 128])
blocks.0.hook_resid_post torch.Size([12000, 64, 128])


In [ ]:
imshow(cache["pattern", 0].mean(dim=0)[:, -1, :], title="Average Attention Pattern per Head", xaxis="Source", yaxis="Head")

In [ ]:
imshow(cache["pattern", 0][6][:, -1, :], title="Average Attention Pattern per Head", xaxis="Source", yaxis="Head",)

In [ ]:
dataset[:4]

tensor([[4, 3, 5, 2, 2, 3, 2, 3, 0, 2, 1, 4, 4, 1, 2, 0, 4, 4, 3, 3, 2, 0, 4, 4,
         0, 2, 3, 1, 3, 0, 3, 2, 4, 4, 3, 2, 1, 1, 0, 1, 2, 4, 1, 3, 2, 2, 5, 5,
         2, 0, 1, 0, 1, 5, 2, 4, 3, 0, 4, 4, 1, 1, 5, 3],
        [1, 0, 3, 5, 4, 4, 1, 0, 3, 2, 3, 3, 3, 5, 4, 1, 1, 3, 3, 4, 1, 1, 1, 3,
         5, 3, 3, 1, 1, 4, 4, 0, 0, 0, 5, 3, 2, 0, 0, 4, 1, 2, 2, 0, 3, 1, 5, 3,
         4, 1, 5, 3, 2, 2, 4, 3, 1, 5, 4, 3, 4, 3, 4, 1],
        [1, 4, 1, 0, 1, 2, 1, 0, 1, 4, 5, 4, 2, 2, 2, 3, 1, 1, 4, 4, 2, 1, 4, 2,
         2, 3, 3, 3, 2, 3, 3, 3, 0, 0, 1, 4, 2, 1, 0, 5, 4, 3, 2, 3, 2, 0, 1, 0,
         5, 1, 0, 5, 0, 5, 4, 4, 5, 3, 5, 5, 3, 4, 5, 4],
        [0, 0, 3, 0, 3, 0, 4, 1, 2, 0, 1, 4, 3, 2, 5, 1, 4, 1, 2, 2, 1, 5, 2, 2,
         0, 5, 2, 0, 1, 0, 2, 5, 0, 0, 3, 5, 0, 2, 1, 3, 1, 0, 3, 4, 1, 5, 0, 3,
         5, 3, 2, 5, 5, 0, 5, 4, 1, 5, 2, 2, 3, 2, 3, 2]], device='cuda:0')

In [ ]:
imshow(cache["pattern", 0][:64, 0, -1, :].reshape(64,64), title="Attention for Head 0", xaxis="characters", yaxis="string")

In [ ]:
imshow(cache["pattern", 0][:64, 1, -1, :].reshape(64,64), title="Attention for Head 1", xaxis="characters", yaxis="string")

In [ ]:
imshow(cache["pattern", 0][:64, 2, -1, :].reshape(64,64), title="Attention for Head 2", xaxis="characters", yaxis="string")

In [ ]:
imshow(cache["pattern", 0][:64, 3, -1, :].reshape(64,64), title="Attention for Head 3", xaxis="characters", yaxis="string")

In [ ]:
# imshow(
    # einops.rearrange(cache["pattern", 0][:, :, -1, 0], "(a b) head -> head a b", a=p, b=p),
    # title="Attention for Head 0 from a -> =", xaxis="b", yaxis="a", facet_col=0)

Plotting neuron activations

In [ ]:
cache["post", 0, "mlp"].shape

torch.Size([12000, 64, 512])

In [ ]:
cache["pattern",0].shape

torch.Size([12000, 4, 64, 64])

In [ ]:
imshow(
    einops.rearrange(neuron_acts[:, :5], "(a b) neuron -> neuron a b", a=p, b=p),
    title="First 5 neuron acts", xaxis="b", yaxis="a", facet_col=0)

EinopsError:  Error while processing rearrange-reduction pattern "(a b) neuron -> neuron a b".
 Input tensor shape: torch.Size([12000, 5]). Additional info: {'a': 51, 'b': 51}.
 Shape mismatch, 12000 != 2601

### Singular Value Decomposition

In [ ]:
W_E.shape

torch.Size([63, 128])

In [ ]:
U, S, Vh = torch.svd(W_E)
line(S, title="Singular Values")
imshow(U, title="Principal Components on the Input")

In [ ]:
# Control - random Gaussian matrix
U, S, Vh = torch.svd(torch.randn_like(W_E))
line(S, title="Singular Values Random")
imshow(U, title="Principal Components Random")

## Explaining Algorithm

### Analyse the Embedding - It's a Lookup Table!

In [ ]:
U, S, Vh = torch.svd(W_E)
line(U[:, :8].T, title="Principal Components of the embedding", xaxis="Input Vocabulary")

In [ ]:
fourier_basis = []
fourier_basis_names = []
fourier_basis.append(torch.ones(p))
fourier_basis_names.append("Constant")
for freq in range(1, p//2+1):
    fourier_basis.append(torch.sin(torch.arange(p)*2 * torch.pi * freq / p))
    fourier_basis_names.append(f"Sin {freq}")
    fourier_basis.append(torch.cos(torch.arange(p)*2 * torch.pi * freq / p))
    fourier_basis_names.append(f"Cos {freq}")
fourier_basis = torch.stack(fourier_basis, dim=0).cuda()
fourier_basis = fourier_basis/fourier_basis.norm(dim=-1, keepdim=True)
imshow(fourier_basis, xaxis="Input", yaxis="Component", y=fourier_basis_names)

In [ ]:
line(fourier_basis[:8], xaxis="Input", line_labels=fourier_basis_names[:8], title="First 8 Fourier Components")
line(fourier_basis[25:29], xaxis="Input", line_labels=fourier_basis_names[25:29], title="Middle Fourier Components")

In [ ]:
imshow(fourier_basis @ fourier_basis.T, title="All Fourier Vectors are Orthogonal")

### Analyse the Embedding

In [ ]:
imshow(fourier_basis @ W_E, yaxis="Fourier Component", xaxis="Residual Stream", y=fourier_basis_names, title="Embedding in Fourier Basis")

RuntimeError: mat1 and mat2 shapes cannot be multiplied (51x51 and 63x128)

In [ ]:
line((fourier_basis @ W_E).norm(dim=-1), xaxis="Fourier Component", x=fourier_basis_names, title="Norms of Embedding in Fourier Basis")

RuntimeError: mat1 and mat2 shapes cannot be multiplied (51x51 and 63x128)

In [ ]:
key_freqs = [17, 25, 32, 47]
key_freq_indices = [33, 34, 49, 50, 63, 64, 93, 94]
fourier_embed = fourier_basis @ W_E
key_fourier_embed = fourier_embed[key_freq_indices]
print("key_fourier_embed", key_fourier_embed.shape)
imshow(key_fourier_embed @ key_fourier_embed.T, title="Dot Product of embedding of key Fourier Terms")

### Key Frequencies

In [ ]:
line(fourier_basis[[34, 50, 64, 94]], title="Cos of key freqs", line_labels=[34, 50, 64, 94])

In [ ]:
line(fourier_basis[[34, 50, 64, 94]].mean(0), title="Constructive Interference")

## Analyse Neurons

In [ ]:
imshow(
    einops.rearrange(neuron_acts[:, :5], "(a b) neuron -> neuron a b", a=p, b=p),
    title="First 5 neuron acts", xaxis="b", yaxis="a", facet_col=0)

In [ ]:
imshow(
    einops.rearrange(neuron_acts[:, 0], "(a b) -> a b", a=p, b=p),
    title="First neuron act", xaxis="b", yaxis="a",)

In [ ]:
imshow(fourier_basis[94][None, :] * fourier_basis[94][:, None], title="Cos 47a * cos 47b")

In [ ]:
imshow(fourier_basis[94][None, :] * fourier_basis[0][:, None], title="Cos 47a * const")

In [ ]:
imshow(fourier_basis @ neuron_acts[:, 0].reshape(p, p) @ fourier_basis.T, title="2D Fourier Transformer of neuron 0", xaxis="b", yaxis="a", x=fourier_basis_names, y=fourier_basis_names)

In [ ]:
imshow(fourier_basis @ neuron_acts[:, 5].reshape(p, p) @ fourier_basis.T, title="2D Fourier Transformer of neuron 5", xaxis="b", yaxis="a", x=fourier_basis_names, y=fourier_basis_names)

In [ ]:
imshow(fourier_basis @ torch.randn_like(neuron_acts[:, 0]).reshape(p, p) @ fourier_basis.T, title="2D Fourier Transformer of RANDOM", xaxis="b", yaxis="a", x=fourier_basis_names, y=fourier_basis_names)

### Neuron Clusters

In [ ]:
fourier_neuron_acts = fourier_basis @ einops.rearrange(neuron_acts, "(a b) neuron -> neuron a b", a=p, b=p) @ fourier_basis.T
# Center these by removing the mean - doesn't matter!
fourier_neuron_acts[:, 0, 0] = 0.
print("fourier_neuron_acts", fourier_neuron_acts.shape)

In [ ]:
neuron_freq_norm = torch.zeros(p//2, model.cfg.d_mlp).cuda()
for freq in range(0, p//2):
    for x in [0, 2*(freq+1) - 1, 2*(freq+1)]:
        for y in [0, 2*(freq+1) - 1, 2*(freq+1)]:
            neuron_freq_norm[freq] += fourier_neuron_acts[:, x, y]**2
neuron_freq_norm = neuron_freq_norm / fourier_neuron_acts.pow(2).sum(dim=[-1, -2])[None, :]
imshow(neuron_freq_norm, xaxis="Neuron", yaxis="Freq", y=torch.arange(1, p//2+1), title="Neuron Frac Explained by Freq")

In [ ]:
line(neuron_freq_norm.max(dim=0).values.sort().values, xaxis="Neuron", title="Max Neuron Frac Explained over Freqs")

## Read Off the Neuron-Logit Weights to Interpret

In [ ]:
W_logit = model.blocks[0].mlp.W_out @ model.unembed.W_U
print("W_logit", W_logit.shape)

In [ ]:
line((W_logit @ fourier_basis.T).norm(dim=0), x=fourier_basis_names, title="W_logit in the Fourier Basis")

In [ ]:
neurons_17 = neuron_freq_norm[17-1]>0.85
neurons_17.shape

In [ ]:
neurons_17.sum()

In [ ]:
line((W_logit[neurons_17] @ fourier_basis.T).norm(dim=0), x=fourier_basis_names, title="W_logit for freq 17 neurons in the Fourier Basis")

Study sin 17

In [ ]:
freq = 17
W_logit_fourier = W_logit @ fourier_basis
neurons_sin_17 = W_logit_fourier[:, 2*freq-1]
line(neurons_sin_17)

In [ ]:
neuron_acts.shape

In [ ]:
inputs_sin_17c = neuron_acts @ neurons_sin_17
imshow(fourier_basis @ inputs_sin_17c.reshape(p, p) @ fourier_basis.T, title="Fourier Heatmap over inputs for sin17c", x=fourier_basis_names, y=fourier_basis_names)

# Black Box Methods + Progress Measures

## Setup Code

Code to plot embedding freqs

In [ ]:
def embed_to_cos_sin(fourier_embed):
    if len(fourier_embed.shape) == 1:
        return torch.stack([fourier_embed[1::2], fourier_embed[2::2]])
    else:
        return torch.stack([fourier_embed[:, 1::2], fourier_embed[:, 2::2]], dim=1)

from neel_plotly.plot import melt

def plot_embed_bars(
    fourier_embed,
    title="Norm of embedding of each Fourier Component",
    return_fig=False,
    **kwargs
):
    cos_sin_embed = embed_to_cos_sin(fourier_embed)
    df = melt(cos_sin_embed)
    # display(df)
    group_labels = {0: "sin", 1: "cos"}
    df["Trig"] = df["0"].map(lambda x: group_labels[x])
    fig = px.bar(
        df,
        barmode="group",
        color="Trig",
        x="1",
        y="value",
        labels={"1": "$w_k$", "value": "Norm"},
        title=title,
        **kwargs
    )
    fig.update_layout(dict(legend_title=""))

    if return_fig:
        return fig
    else:
        fig.show()

Code to test a tensor of edited logits

In [ ]:
def test_logits(logits, bias_correction=False, original_logits=None, mode="all"):
    # Calculates cross entropy loss of logits representing a batch of all p^2
    # possible inputs
    # Batch dimension is assumed to be first
    if logits.shape[1] == p * p:
        logits = logits.T
    if logits.shape == torch.Size([p * p, p + 1]):
        logits = logits[:, :-1]
    logits = logits.reshape(p * p, p)
    if bias_correction:
        # Applies bias correction - we correct for any missing bias terms,
        # independent of the input, by centering the new logits along the batch
        # dimension, and then adding the average original logits across all inputs
        logits = (
            einops.reduce(original_logits - logits, "batch ... -> ...", "mean") + logits
        )
    if mode == "train":
        return loss_fn(logits[train_indices], labels[train_indices])
    elif mode == "test":
        return loss_fn(logits[test_indices], labels[test_indices])
    elif mode == "all":
        return loss_fn(logits, labels)

Code to run a metric over every checkpoint

In [ ]:
metric_cache = {}

In [ ]:
def get_metrics(model, metric_cache, metric_fn, name, reset=False):
    if reset or (name not in metric_cache) or (len(metric_cache[name]) == 0):
        metric_cache[name] = []
        for c, sd in enumerate(tqdm.tqdm((model_checkpoints))):
            model.reset_hooks()
            model.load_state_dict(sd)
            out = metric_fn(model)
            if type(out) == torch.Tensor:
                out = utils.to_numpy(out)
            metric_cache[name].append(out)
        model.load_state_dict(model_checkpoints[-1])
        try:
            metric_cache[name] = torch.tensor(metric_cache[name])
        except:
            metric_cache[name] = torch.tensor(np.array(metric_cache[name]))



## Defining Progress Measures

### Loss Curves

In [ ]:
memorization_end_epoch = 1500
circuit_formation_end_epoch = 13300
cleanup_end_epoch = 16600

In [ ]:
def add_lines(figure):
    figure.add_vline(memorization_end_epoch, line_dash="dash", opacity=0.7)
    figure.add_vline(circuit_formation_end_epoch, line_dash="dash", opacity=0.7)
    figure.add_vline(cleanup_end_epoch, line_dash="dash", opacity=0.7)
    return figure

In [ ]:
fig = line([train_losses[::100], test_losses[::100]], x=np.arange(0, len(train_losses), 100), xaxis="Epoch", yaxis="Loss", log_y=True, title="Training Curve for Modular Addition", line_labels=['train', 'test'], toggle_x=True, toggle_y=True, return_fig=True)
add_lines(fig)

### Logit Periodicity

In [ ]:
all_logits = original_logits[:, -1, :]
print(all_logits.shape)
all_logits = einops.rearrange(all_logits, "(a b) c -> a b c", a=p, b=p)
print(all_logits.shape)

In [ ]:
coses = {}
for freq in key_freqs:
    print("Freq:", freq)
    a = torch.arange(p)[:, None, None]
    b = torch.arange(p)[None, :, None]
    c = torch.arange(p)[None, None, :]
    cube_predicted_logits = torch.cos(freq * 2 * torch.pi / p * (a + b - c)).cuda()
    cube_predicted_logits /= cube_predicted_logits.norm()
    coses[freq] = cube_predicted_logits

In [ ]:
approximated_logits = torch.zeros_like(all_logits)
for freq in key_freqs:
    print("Freq:", freq)
    coeff = (all_logits * coses[freq]).sum()
    print("Coeff:", coeff)
    cosine_sim = coeff / all_logits.norm()
    print("Cosine Sim:", cosine_sim)
    approximated_logits += coeff * coses[freq]
residual = all_logits - approximated_logits
print("Residual size:", residual.norm())
print("Residual fraction of norm:", residual.norm()/all_logits.norm())

In [ ]:
random_logit_cube = torch.randn_like(all_logits)
print((all_logits * random_logit_cube).sum()/random_logit_cube.norm()/all_logits.norm())

In [ ]:
test_logits(all_logits)

In [ ]:
test_logits(approximated_logits)

#### Look During Training

In [ ]:
cos_cube = []
for freq in range(1, p//2 + 1):
    a = torch.arange(p)[:, None, None]
    b = torch.arange(p)[None, :, None]
    c = torch.arange(p)[None, None, :]
    cube_predicted_logits = torch.cos(freq * 2 * torch.pi / p * (a + b - c)).cuda()
    cube_predicted_logits /= cube_predicted_logits.norm()
    cos_cube.append(cube_predicted_logits)
cos_cube = torch.stack(cos_cube, dim=0)
print(cos_cube.shape)

In [ ]:
def get_cos_coeffs(model):
    logits = model(dataset)[:, -1]
    logits = einops.rearrange(logits, "(a b) c -> a b c", a=p, b=p)
    vals = (cos_cube * logits[None, :, :, :]).sum([-3, -2, -1])
    return vals


get_metrics(model, metric_cache, get_cos_coeffs, "cos_coeffs")
print(metric_cache["cos_coeffs"].shape)

In [ ]:
fig = line(metric_cache["cos_coeffs"].T, line_labels=[f"Freq {i}" for i in range(1, p//2+1)], title="Coefficients with Predicted Logits", xaxis="Epoch", x=checkpoint_epochs, yaxis="Coefficient", return_fig=True)
add_lines(fig)

In [ ]:
def get_cos_sim(model):
    logits = model(dataset)[:, -1]
    logits = einops.rearrange(logits, "(a b) c -> a b c", a=p, b=p)
    vals = (cos_cube * logits[None, :, :, :]).sum([-3, -2, -1])
    return vals / logits.norm()

get_metrics(model, metric_cache, get_cos_sim, "cos_sim") # You may need a big GPU. If you don't have one and can't work around this, raise an issue for help!
print(metric_cache["cos_sim"].shape)

fig = line(metric_cache["cos_sim"].T, line_labels=[f"Freq {i}" for i in range(1, p//2+1)], title="Cosine Sim with Predicted Logits", xaxis="Epoch", x=checkpoint_epochs, yaxis="Cosine Sim", return_fig=True)
add_lines(fig)

In [ ]:
def get_residual_cos_sim(model):
    logits = model(dataset)[:, -1]
    logits = einops.rearrange(logits, "(a b) c -> a b c", a=p, b=p)
    vals = (cos_cube * logits[None, :, :, :]).sum([-3, -2, -1])
    residual = logits - (vals[:, None, None, None] * cos_cube).sum(dim=0)
    return residual.norm() / logits.norm()

get_metrics(model, metric_cache, get_residual_cos_sim, "residual_cos_sim")
print(metric_cache["residual_cos_sim"].shape)

fig = line([metric_cache["cos_sim"][:, i] for i in range(p//2)]+[metric_cache["residual_cos_sim"]], line_labels=[f"Freq {i}" for i in range(1, p//2+1)]+["residual"], title="Cosine Sim with Predicted Logits + Residual", xaxis="Epoch", x=checkpoint_epochs, yaxis="Cosine Sim", return_fig=True)
add_lines(fig)

## Restricted Loss

In [ ]:
neuron_acts.shape

In [ ]:
neuron_acts_square = einops.rearrange(neuron_acts, "(a b) neur -> a b neur", a=p, b=p).clone()
# Center it
neuron_acts_square -= einops.reduce(neuron_acts_square, "a b neur -> 1 1 neur", "mean")
neuron_acts_square_fourier = einsum("a b neur, fa a, fb b -> fa fb neur", neuron_acts_square, fourier_basis, fourier_basis)
imshow(neuron_acts_square_fourier.norm(dim=-1), xaxis="Fourier Component b", yaxis="Fourier Component a", title="Norms of neuron activations by Fourier Component", x=fourier_basis_names, y=fourier_basis_names)

In [ ]:
original_logits, cache = model.run_with_cache(dataset)
print(original_logits.numel())
neuron_acts = cache["post", 0, "mlp"][:, -1, :]

In [ ]:
approx_neuron_acts = torch.zeros_like(neuron_acts)
approx_neuron_acts += neuron_acts.mean(dim=0)
a = torch.arange(p)[:, None]
b = torch.arange(p)[None, :]
for freq in key_freqs:
    cos_apb_vec = torch.cos(freq * 2 * torch.pi / p * (a + b)).cuda()
    cos_apb_vec /= cos_apb_vec.norm()
    cos_apb_vec = einops.rearrange(cos_apb_vec, "a b -> (a b) 1")
    approx_neuron_acts += (neuron_acts * cos_apb_vec).sum(dim=0) * cos_apb_vec
    sin_apb_vec = torch.sin(freq * 2 * torch.pi / p * (a + b)).cuda()
    sin_apb_vec /= sin_apb_vec.norm()
    sin_apb_vec = einops.rearrange(sin_apb_vec, "a b -> (a b) 1")
    approx_neuron_acts += (neuron_acts * sin_apb_vec).sum(dim=0) * sin_apb_vec
restricted_logits = approx_neuron_acts @ W_logit
print(loss_fn(restricted_logits[test_indices], test_labels))

In [ ]:
print(loss_fn(all_logits, labels)) # This bugged on models not fully trained

### Look During Training

In [ ]:
def get_restricted_loss(model):
    logits, cache = model.run_with_cache(dataset)
    logits = logits[:, -1, :]
    neuron_acts = cache["post", 0, "mlp"][:, -1, :]
    approx_neuron_acts = torch.zeros_like(neuron_acts)
    approx_neuron_acts += neuron_acts.mean(dim=0)
    a = torch.arange(p)[:, None]
    b = torch.arange(p)[None, :]
    for freq in key_freqs:
        cos_apb_vec = torch.cos(freq * 2 * torch.pi / p * (a + b)).cuda()
        cos_apb_vec /= cos_apb_vec.norm()
        cos_apb_vec = einops.rearrange(cos_apb_vec, "a b -> (a b) 1")
        approx_neuron_acts += (neuron_acts * cos_apb_vec).sum(dim=0) * cos_apb_vec
        sin_apb_vec = torch.sin(freq * 2 * torch.pi / p * (a + b)).cuda()
        sin_apb_vec /= sin_apb_vec.norm()
        sin_apb_vec = einops.rearrange(sin_apb_vec, "a b -> (a b) 1")
        approx_neuron_acts += (neuron_acts * sin_apb_vec).sum(dim=0) * sin_apb_vec
    restricted_logits = approx_neuron_acts @ model.blocks[0].mlp.W_out @ model.unembed.W_U
    # Add bias term
    restricted_logits += logits.mean(dim=0, keepdim=True) - restricted_logits.mean(dim=0, keepdim=True)
    return loss_fn(restricted_logits[test_indices], test_labels)
get_restricted_loss(model)

In [ ]:
get_metrics(model, metric_cache, get_restricted_loss, "restricted_loss", reset=True)
print(metric_cache["restricted_loss"].shape)

In [ ]:
fig = line([train_losses[::100], test_losses[::100], metric_cache["restricted_loss"]], x=np.arange(0, len(train_losses), 100), xaxis="Epoch", yaxis="Loss", log_y=True, title="Restricted Loss Curve", line_labels=['train', 'test', "restricted_loss"], toggle_x=True, toggle_y=True, return_fig=True)
add_lines(fig)

In [ ]:
fig = line([torch.tensor(test_losses[::100])/metric_cache["restricted_loss"]], x=np.arange(0, len(train_losses), 100), xaxis="Epoch", yaxis="Loss", log_y=True, title="Restricted Loss to Test Loss Ratio", toggle_x=True, toggle_y=True, return_fig=True)
# WARNING: bugged when cancelling training half way thr ough
add_lines(fig)

## Excluded Loss

In [ ]:
approx_neuron_acts = torch.zeros_like(neuron_acts)
# approx_neuron_acts += neuron_acts.mean(dim=0)
a = torch.arange(p)[:, None]
b = torch.arange(p)[None, :]
for freq in key_freqs:
    cos_apb_vec = torch.cos(freq * 2 * torch.pi / p * (a + b)).cuda()
    cos_apb_vec /= cos_apb_vec.norm()
    cos_apb_vec = einops.rearrange(cos_apb_vec, "a b -> (a b) 1")
    approx_neuron_acts += (neuron_acts * cos_apb_vec).sum(dim=0) * cos_apb_vec
    sin_apb_vec = torch.sin(freq * 2 * torch.pi / p * (a + b)).cuda()
    sin_apb_vec /= sin_apb_vec.norm()
    sin_apb_vec = einops.rearrange(sin_apb_vec, "a b -> (a b) 1")
    approx_neuron_acts += (neuron_acts * sin_apb_vec).sum(dim=0) * sin_apb_vec
excluded_neuron_acts = neuron_acts - approx_neuron_acts
excluded_logits = excluded_neuron_acts @ W_logit
print(loss_fn(excluded_logits[train_indices], train_labels))

In [ ]:
def get_excluded_loss(model):
    logits, cache = model.run_with_cache(dataset)
    logits = logits[:, -1, :]
    neuron_acts = cache["post", 0, "mlp"][:, -1, :]
    approx_neuron_acts = torch.zeros_like(neuron_acts)
    # approx_neuron_acts += neuron_acts.mean(dim=0)
    a = torch.arange(p)[:, None]
    b = torch.arange(p)[None, :]
    for freq in key_freqs:
        cos_apb_vec = torch.cos(freq * 2 * torch.pi / p * (a + b)).cuda()
        cos_apb_vec /= cos_apb_vec.norm()
        cos_apb_vec = einops.rearrange(cos_apb_vec, "a b -> (a b) 1")
        approx_neuron_acts += (neuron_acts * cos_apb_vec).sum(dim=0) * cos_apb_vec
        sin_apb_vec = torch.sin(freq * 2 * torch.pi / p * (a + b)).cuda()
        sin_apb_vec /= sin_apb_vec.norm()
        sin_apb_vec = einops.rearrange(sin_apb_vec, "a b -> (a b) 1")
        approx_neuron_acts += (neuron_acts * sin_apb_vec).sum(dim=0) * sin_apb_vec
    excluded_neuron_acts = neuron_acts - approx_neuron_acts
    residual_stream_final = excluded_neuron_acts @ model.blocks[0].mlp.W_out + cache["resid_mid", 0][:, -1, :]
    excluded_logits = residual_stream_final @ model.unembed.W_U
    return loss_fn(excluded_logits[train_indices], train_labels)
get_excluded_loss(model)

In [ ]:
get_metrics(model, metric_cache, get_excluded_loss, "excluded_loss", reset=True)
print(metric_cache["excluded_loss"].shape)

In [ ]:
fig = line([train_losses[::100], test_losses[::100], metric_cache["excluded_loss"], metric_cache["restricted_loss"]], x=np.arange(0, len(train_losses), 100), xaxis="Epoch", yaxis="Loss", log_y=True, title="Excluded and Restricted Loss Curve", line_labels=['train', 'test', "excluded_loss", "restricted_loss"], toggle_x=True, toggle_y=True, return_fig=True)

add_lines(fig)